MyBlog/MyBlog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MyBlog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include('auth_module.urls', namespace="auth_module")),
)

MyBlog/auth_module/urls.py
from django.conf.urls import patterns, url

from auth_module import views

urlpatterns = patterns('',
                       url(r'^login/$', views.login_action, name='login'),
                       url(r'^$', views.login_action, name='index'),
                       url(r'^registration/$', views.registration, name='registration'),
                       url(r'^logout/$', views.log_out_action, name='logout'),
)

MyBlog/auth_module/models.py
from django.db import models

# Create your models here.

MyBlog/auth_module/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

# Create your views here.

def login_action(request):
    if request.method == 'POST':
        username = request.POST['login']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponse("You was successfuly logged in!")
        else:
            return HttpResponse("Fail of login!")

    if request.method == 'GET':
        if request.user.is_authenticated():
            return HttpResponse("You're already logged in!")
        return render(request, 'auth_module/login.html')


def registration(request):
    if request.method == 'GET':
        return render(request, 'auth_module/registration.html')
    if request.method == 'POST':
        username = request.POST['login']
        email = request.POST['email']
        password = request.POST['password']
        c_password = request.POST['c_password']
        if password == c_password:
            try:
                user = User.objects.create_user(username, email, password);
                user.save()
                return render(request, 'auth_module/login.html')
            except ValueError as e:
                return render(request, 'auth_module/registration.html', {'error' : e.__str__()})
        else:
            return render(request, 'auth_module/registration.html', {'error' : 'Passwords doesn`t match!'})

def log_out_action(request):
    logout(request)
    return render(request, 'auth_module/login.html')

MyBlog/templates/auth_module/login.html
{% load staticfiles %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'all/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'auth_module/css/login.css' %}">
</head>
<body>

<div class="form-container">
    <h1>Login</h1>
    <form action="{% url 'auth_module:login' %}" method="post">
        {% csrf_token %}
        <input class="form-control" type="text" name="login" placeholder="Login">
        <input class="form-control" type="password" name="password" placeholder='Password'>
        <input class="btn btn-default" type="submit" value="Sign In">
        <a class="reg_ref" href="{% url 'auth_module:registration' %}">You can register now!</a>
    </form>
</div>
</body>
</html>

MyBlog/templates/auth_module/registration.html
{% load staticfiles %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'all/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'auth_module/css/registration.css' %}">
</head>
<body>
	<div class="form-container">
		<h1>Registration</h1>
        <form action="{% url 'auth_module:registration' %}" method="post">
            {% csrf_token %}
            <input class="form-control" type="text" name="login" placeholder="Username">
            <input class="form-control" type="email" name="email" placeholder="Email">
            <input class="form-control" type="password" name="password" placeholder="Password">
            <input class="form-control" type="password" name="c_password" placeholder="Confirm password">
            <input class="btn btn-default" type="submit" value="Sign Up!">
            <a class="log_ref" href="{% url 'auth_module:index' %}">You can sign in</a>
            {% if error %} <div class="error">{{error}}</div>{% endif %}
		</form>
	</div>

</body>
</html>